### ISSUE TITLE
Control over method names

### ISSUE THREAD

**Issue by orenbenkiki** [yangby-cryptape/rust-property#1]
First, thanks for this!

I find this most useful for allowing read-only access to some data members. I guess being able to allow for setters and `get_mut` is useful in some cases (though why would anyone want a private setter?). But so far, my main usage pattern is:

```
#[derive(Property)]
#[property(get(public), set(disable), get_mut(disable))]
struct Foo {
    bar: Bar,
    ...
}
```

It would be nice if this combination was the default (the only safer combination is disabling everything). But of course, writing this single line is a pleasant alternative to writing all these getters...

Speaking of getters, I find the `get_` method prefix to be an eyesore. I'd rather write `foo.bar()` to access the `bar` data member. Likewise, if I offered mutable access, I'd rather call it `foo.mut_bar()`.

I understand the need to distinguish between the three method families. A `set_` prefix makes sense. But for getters, whether or not one wishes to have `get_` prefix seems debatable.

So... is there any chance to have a `#[property(get_prefix(disable), ...)]` or something along these lines?

**Comment by chaoticlonghair** [comment]
Thanks for your suggestion!

> It would be nice if this combination was the default ...

`pub(crate)` is the default visibility for all `getter` and `setter`.

I think it's safe enough for most cases.

> So... is there any chance to have a `#[property(get_prefix(disable), ...)]` or something along these lines?

I will do this feature in few days, asap.
(I have to finish several tasks for my job before I have time to do this).

In next version, I will try adding three attributes: `name`, `prefix`, `suffix`.

Then, users can define names like this: 

```rust
#[derive(Property)]
#[property(get(prefix = "get_"), get_mut(prefix = "", suffix = "_mut"))]
struct Foo {
    #[property(get(name = "read_bar"))]
    bar: Bar,
    ...
}
```

And, if nobody like the `get(prefix = "get_")` prefix, I will set `get(prefix = "")` as the default (**BREAKING CHANGE**).

**Comment by Schyrsivochter** [comment]
Just found this crate and it’s exactly what I’d like, _except_ for the naming convention with `get_*`. I’d love for this to be implemented.

**Comment by chaoticlonghair** [comment]
I have finished this feature, and I will publish a new version in few hours.

But, to be honest, I didn't do enough tests.

**Comment by orenbenkiki** [comment]
Just tried it, seems to work fine. Thanks!
