### ISSUE TITLE
[Feature Request] Return type of `set` be the old value?

### ISSUE THREAD

**Issue by Karrq** [yangby-cryptape/rust-property#10]
Hello,
thank you for this amazing crate!

I've used it to replace a bunch of my hand-made code and it was a breeze!
The only thing I wish was for another `type` setting for `set`, where the input is an unique reference to the struct, along with an owned version of `T` we are replacing, and the return type is the previous `T`...

Basically a `replace` setting where the generated code does something along:
```rust
#[inline]
fn set_foo<T: Into<Foo>>(&mut self, foo: T) -> Foo {
    std::mem::replace(&mut self.foo, foo.into())
} 
```

Thanks a bunch!!

**Comment by chaoticlonghair** [comment]
Thanks for your suggestion!

Since I don't have free time before this weekend, I will implement your proposed feature in Sunday and release a new version in next week if things goes well.

**Comment by chaoticlonghair** [comment]
DONE! [v0.3.3](https://crates.io/crates/property/0.3.3) is released.
