### ISSUE TITLE
Does "inline" really impact performance?

### ISSUE THREAD

**Issue by matthiasbeyer** [yangby-cryptape/rust-property#4]
Hi,

did you actually measure whether the `#[inline(always)]` decoration has any influence on the performance of the generated code?

As far as I know, the rust compiler is good enough with inlining (or rather with not inlining) to optimize for performance, thus one should never force inline for code.

I might be wrong, though. Would be nice if we could measure here, before optimizing something that might not need to be optimized...

**Comment by chaoticlonghair** [comment]
Thanks for your advice.

I shouldn't use `#[inline(always)]`. It was a typo.

I didn't test this crate, but I had tested `inline` in my other crates.
**Sometimes it improves performance, and sometimes it reduces performance.**

I will remove the `always`, just leave `#[inline]`.

**Comment by matthiasbeyer** [comment]
Sounds like the right way, thank you!

**Comment by chaoticlonghair** [comment]
I have released [a new version](https://github.com/yangby-cryptape/rust-property/compare/v0.3.0...v0.3.1) to fix it.
